### PR TITLE
Work on #4

### LINKED ISSUE #4: Breakdown of meta community model
As requested a breakdown of the model and its terms

### PR DESCRIPTION
**Pull request by tpoisot**
Immigration is _not_ to blame, it's one of the other three (cc @TanyaS08)

Closes #4

### CODE REVIEW

**Comment by tpoisot** [comment]
I will also refactor some of the code internally to make it a little easier to see what's going on, there's a lot of arguments that aren't needed

**Comment by TanyaS08** [comment]
> Immigration is _not_ to blame, it's one of the other three (cc @TanyaS08)
> 
> Closes #4

I'm taking this fact as a big **W** because it means the months (okay more like days) of breaking and unbreaking my understanding of basic geometry/pythag theorem was not in vain

**Comment by TanyaS08** [comment]
all_test

this sparks joy given where we started

**Comment by tpoisot** [comment]
So, @TanyaS08 , I *think* the issue is that the scaling parameter of h = 300 is essentially specific to the simulation they used. My guess would be that we can pick landscape values between -1 and 1 (for example) and use much smaller parameters for the effect of the environment.

Otherwise, the environment term in the model gets SUPER big, and there's exponential growth of everything, which kills plants, and allows other species to persist.

**Comment by tpoisot** [comment]
I'm going to stop there for the week-end, but I think (1) the code is probably right and (2) there's going to be some pen and paper work to figure out values of h and sigma

**Comment by TanyaS08** [comment]
Yay! An excuse to whip out the new pen and inks (and use the fancy paper)!🦄 I’ll work on some things next week 🫡Am 2023-05-19 um 17:42 schrieb Timothée Poisot ***@***.***>:﻿
I'm going to stop there for the week-end, but I think (1) the code is probably right and (2) there's going to be some pen and paper work to figure out values of h and sigma

**Comment by tpoisot** [comment]
I think I got it. What the original code does is

A1 = h × exp(bleh)

and then A = A1 - max (A1)

But we don't need to calculate the max here because we know A is maximized at the optimum, and exp(bleh)  at the optimum is 1, so A at the optimum is h

Putting things together we get

A = h × exp(bleh) - h

Which is A = h × (exp(bleh) - 1)

So worst case scenario, a species with exp(bleh) ~ 0 has A = -h, and as soon as r - h < 0, because it's exponentiated in the end, the population size decreases. 

I think it's just the terms in the effect equation in the original paper that have been swapped.

**Comment by tpoisot** [comment]
I found a few more things in the code, so we're getting there. There is an issue with dispersal, but now I know what it is and how to fix it so it's cool.

**Comment by TanyaS08** [comment]
> I think I got it. What the original code does is
> 
> A1 = h × exp(bleh)
> 
> and then A = A1 - max (A1)
> 
> But we don't need to calculate the max here because we know A is maximized at the optimum, and exp(bleh) at the optimum is 1, so A at the optimum is h
> 
> Putting things together we get
> 
> A = h × exp(bleh) - h
> 
> Which is A = h × (exp(bleh) - 1)
> 
> So worst case scenario, a species with exp(bleh) ~ 0 has A = -h, and as soon as r - h < 0, because it's exponentiated in the end, the population size decreases.
> 
> I think it's just the terms in the effect equation in the original paper that have been swapped.

Pen and paper method agrees with the swop (paper version 'minimises' at what would be best case (env = env optimum)) I am questioning the new parameters (see 'modded')  that you introduced with commit 3b44d22 (i.e. h and σ) since that does throw out the 'scaling' of the env effect. Note here the env values range is that used by Thompson (1 - 80)

plot_116

Even if we restrict the environment to a much smaller range the env effect is teenier than tiny

plot_117

I'm of the mind path of least resistance is having the Env effect be in the same range as Thompson vals are

**Comment by TanyaS08** [comment]
plot_119

Will still fur sure have to modify the Thompson params though

**Comment by TanyaS08** [comment]
May I suggest:

h = 4000,
σ = 5

Its behaving in a similar manner to the Thompson model in terms of Environmental effect

plot_129

**Comment by tpoisot** [comment]
I like these parameter values!

**Comment by tpoisot** [comment]
I've just pushed a version with cleaner code -- can you run check that the parameters are working?

**Pull request merged**
